name: Deploy Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 部署 Main 分支到根目录
      - name: Deploy Main to Root
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true # 🌟 关键修复：防止清空 dev 预览文件夹

      # 部署 Dev 分支到 dev 子目录
      - name: Deploy Dev to Preview Folder
        if: github.ref == 'refs/heads/dev'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          destination_dir: dev
          keep_files: true # 🌟 关键修复：防止清空 main 主目录